### ISSUE TITLE
GUI空缺内容填补

### ISSUE THREAD

**Issue by Pscgylotti** [USTC-tuixue/Arcane-Art#22]
1.ManaBar与玩家魔力关联
2.MagicMenu的成书刻录为法术

**Comment by TowardtheStars** [comment]
![图片](https://user-images.githubusercontent.com/29396015/88462515-763d1e80-cede-11ea-9488-8f06aedad4ea.png)
你要不改一下变量名或者加个注释？不然我真的不清楚哪个槽都是啥
