### ISSUE TITLE
Game crashes when pointing to solar crystal in creative mode inventory

### ISSUE THREAD

**Issue by KeithTsao** [USTC-tuixue/Arcane-Art#37]
As title says, and log reports as below:
>......
>Caused by: java.lang.ClassCastException: com.ustctuixue.arcaneart.api.spell.TranslatedSpell cannot be cast to com.ustctuixue.arcaneart.api.spell.ITranslatedSpellProvider
>	at com.ustctuixue.arcaneart.api.spell.ItemSpell.getSpellProvider(ItemSpell.java:34) ~[main/:?] {re:classloading}
>	at com.ustctuixue.arcaneart.api.spell.ItemSpell.getSpell(ItemSpell.java:28) ~[main/:?] {re:classloading}
>	at com.ustctuixue.arcaneart.api.spell.ItemSpell.getDisplayName(ItemSpell.java:22) ~[main/:?] {re:classloading}
>	at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:585) ~[forge-1.15.2-31.2.0_mapped_snapshot_20200514-1.15.1-recomp.jar:?] {re:classloading}
>	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:631) ~[forge-1.15.2-31.2.0_mapped_snapshot_20200514-1.15.1-recomp.jar:?] {re:classloading}
>......

**Comment by TowardtheStars** [comment]
已解决
